### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed 

### ISSUE THREAD

**Issue by Rahulkumar-G** [awslabs/aws-lex-browser-audio-capture#11]
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'.

My CSP doesn't allow script evaluation. how can we make this covered considering XSS attacks for this library.?

**Comment by glmourad** [comment]
Could you edit the CSP values? In my case I appended `worker-src 'self' 'unsafe-inline' 'unsafe-eval' *.amazonaws.com blob:;` to my csp policy
