### ISSUE TITLE
Records only 0s on Chrome (v42 or later) when hosted on http://localhost

### ISSUE THREAD

**Issue by ryano144** [awslabs/aws-lex-browser-audio-capture#2]
In using this on Google Chrome, the audioSupported check passes, but the audio buffer returned by getChannelData(0) only contains 0s.  I think this may be due to the addition of CORS checks for MediaElementAudioSource in chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=477364.

**Comment by palafranchise** [comment]
Thanks for reporting the issue! I just tried it out with my laptop running locally (http://localhost:8000/example/) on Mac/Chrome (Version 61.0.3163.100 (Official Build) (64-bit)) and I'm not seeing the issue. Can you provide more information about the version of Chrome you are using and your OS? I assume you have allowed access to the microphone for localhost or you would not be getting this far but can you confirm that too?

**Comment by ryano144** [comment]
I was running in Chrome 60.0.3112.113.  I did allow access to the microphone for localhost.  I've since attempted to host the platform on the web under https and got the same results (all 0s returned by audioProcessingEvent.inputBuffer.getChannelData).

**Comment by palafranchise** [comment]
Hmm, okay. Which operating system are you using? I'll try to reproduce. 

One other thing to try, and I know this sounds silly, can you shut down and restart Chrome (or confirm that you have already done that)?

**Comment by ryano144** [comment]
Sorry to have wasted your time.  It looks like I inserted an extra call to worker.clear which was breaking the recording function.

**Comment by palafranchise** [comment]
No worries, happy to help out. Thanks for following up!
