### ISSUE TITLE
Getting: "Recorder not supported" error in safari 10.1 and IE11

### ISSUE THREAD

**Issue by rakesh456** [awslabs/aws-lex-browser-audio-capture#3]
Hi,
Can we use this script on Safari 10.1 & IE 11?

thanks for your answer.
-Rakesh

**Comment by palafranchise** [comment]
Hi Rakesh,

Unfortunately this example is using MediaDevices.getUserMedia (https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) which is not supported in Safari 10.1 or IE 11.

Andrew
