### ISSUE TITLE
Add package.json so we can build it

### ISSUE THREAD

**Issue by ejfrancis** [awslabs/aws-lex-browser-audio-capture#9]
As title suggests, there should be a package.json so we can fork and build this ourselves. It has a gruntfile but that doesn't work unless the accompanying package.json with dependencies and scripts is included as well.

**Comment by palafranchise** [comment]
Done. :-)

Obligatory disclaimer: this is example code written to complement a blog post. More info: https://aws.amazon.com/blogs/machine-learning/capturing-voice-input-in-a-browser/
